---
abstract: 'use National Geographic daily photo of the day as desktop background'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.100900'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ng-daily-wallpaper
recommends: {}
requires:
  File::Path: 0
  Getopt::Long: 0
  Imager: 0
  POSIX: 0
  Pod::Usage::CommandLine: 0
  WWW::Mechanize: 0
  X11::Resolution: 0
  autodie: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=ng-daily-wallpaper
  homepage: http://search.cpan.org/dist/ng-daily-wallpaper/
  repository: http://github.com/mschout/ng-daily-wallpaper
version: 0.02
